### ISSUE TITLE
WEB UI only shows default sinks

### ISSUE THREAD

**Issue by RagingHerring** [BaReinhard/iOS-Audio-to-ChromeCast#11]
This is probably an easy to resolve issue and I'm only missing something, but I'm rather a newbie and actually just got the Raspberry Pi 3 for this Multiroom purpose (great work, btw!):
I have installed everything on Ubuntu Mate as described. However, after rebooting, the system only gets to the Ubuntu Mate splash screen and just turns black with no further OS UI accessible after that. Also no keyboard or other inputs seem to work. 
I do see the set-up RPi as an AirPlay device on my iOS devices and can also access the WEB UI via the RPi's IP address, though. On the WEB UI I unfortunately only see the default sinks and cannot connect to any of my Chromecast devices.
So I assume if I could tell the RPi to search for my Chromecast devices/update the WEB UI, this would all work like a charm. Any ideas how I could resolve these issues?

**Comment by nachochip** [comment]
I want to add to this:  
- I manually ran executeJson.sh and it failed.  (the /public/app/ folder has restricted write permissions)
- I manually ran the contents to another file. Then manually moved it out to the appropriate folder.
         ~/genSinks.sh > ~/sinks.json
         sudo mv ~/sinks.json ~/projects/node/public/app/sinks.json
- After doing this, the Web UI was specific to my home setup.

@BaReinhard : I would suggest modifying the executeJson.sh to above mentioned code.  That or perhaps modify the app folder permissions, which I haven't looked into.

**Comment by BaReinhard** [comment]
I will have to look into it, the directory should be writable to all users. A quick fix would be to recursively chmod the projects folder to 777, there really isn't any security risks in doing so, but I'll be sure to add that into the install if that is the case. Unfortunately, my time has been extremely limited with this project, I'll try to get this functioning asap

**Comment by nachochip** [comment]
Yes, that works too.

@RagingHerring : This code will fix write access for all users.
         sudo chmod -R +w ~/projects
Then run ~/executeJson.sh manually in a terminal and it worked for me.

@BaReinhard : I will look into the "Refresh Sinks" function on the WEB UI.....I don't see it actually working, I noticed that it is supposed to call the executeJson.sh function, but when I test it, it doesn't really run executeJson.sh.  Not tonight, but hopefully soon, I can get my brain wrapped onto why.

**Comment by BaReinhard** [comment]
My guess would be that execute JSON doesn't have executable permissions, I believe I have to update the Ajax call to wait X amount of seconds then query .json file

**Comment by BaReinhard** [comment]
I finally had some time to actually look at this issue. Among fixing pulseaudio to work properly with the latest Ubuntu MATE 16.04 I was also able to track down why things were updating for the sinks. I still need to issue a fix for that, but it has to do with reading the .json file. This can either be done server side or on the front end. I will likely choose to do so on the server side because that is the proper way to do it, but I can apply a bandaid fix to the front end until I get a chance to look at the server code. I will be doing some testing for this in the coming week and ensure that everything works properly.

I am also choosing to move some of these executable files from the home directory to /usr/local/bin as it just seems a more fitting location for it.

**Comment by BaReinhard** [comment]
I have found a working fix that won’t require any refreshing of the page. I’ll make a pull request with the changes. It won’t be up until maybe Friday, but depending on my daughters nap tomorrow there could be a fix by 2 tomorrow.

**Comment by BaReinhard** [comment]
Latest version of master has fixed this issue.
